/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.9.1/userguide/building_java_projects.html
 */





plugins {
    application
    id("org.openjfx.javafxplugin") version "0.1.0"
}

repositories {

    mavenCentral()
}
javafx {
    version = "17.0.7"
    modules = listOf("javafx.controls", "javafx.fxml", "javafx.graphics")
}
dependencies {

    testImplementation("junit:junit:4.13")

    implementation("com.google.guava:guava:29.0-jre")
    implementation("org.openjfx:javafx:17.0.7")
}

application {
    mainClass.set("CSNETWK_MP_Applications.App") 
}